FIXED_INVERT_EGG = True
FIXED_DBSCAN_EPS = 5
FIXED_DBSCAN_MIN_SAMPLES = 2
FIXED_FALLBACK_A_THRESH = 20
FIXED_OVERLAP_THRESHOLD = 0.1
FIXED_IOU_THRESHOLD = 0.8

TARGET_SIZE = (28, 28)
DILATE_KERNEL_SIZE = 3
BLUR_KSIZE = (3, 3)
BLUR_SIGMA = 0.8

CNN_WEIGHTS_PATH = "weights/skeleton_dots_cnn.pth"